### ISSUE TITLE
Import declaration conflicts with local declaration of 'Document'

### ISSUE THREAD

**Issue by HayatoKamono** [motemen/dts-google-apps-script#2]
`let document: Document = XmlService.parse(xml);`

↑GoogleAppsScript.XML_Service.DocumentとtypescriptのDocumentがコンフリクトしてしまいます。

このような場合はXmlServiceのindex.d.tsの中にあるDocumentを他の名称に変えて対応する以外に方法はあるのでしょうか？

**Comment by motemen** [comment]
再現できないので一般論ですが `let document: GoogleAppsScript.XML_Service.Document = XmlService.parse(xml);` とかですかね。index.d.ts というファイルはこのリポジトリには存在しないので別の話をされているのではないかとも思いますが
